### ISSUE TITLE
Snapshot rafaelzdd

### ISSUE THREAD

**Issue by rafaelzdd** [Acrisio-Filho/TH-Snapshot#1]
[game_packets-rafaelzdd.json](https://github.com/Acrisio-Filho/TH-Snapshot/files/15210792/game_packets-rafaelzdd.json)
[login_packets-rafaelzdd.json](https://github.com/Acrisio-Filho/TH-Snapshot/files/15210793/login_packets-rafaelzdd.json)

**Comment by Acrisio-Filho** [comment]
Obrigado por compartilha o seu snapshot, já adicionei ele na lista de snapshots.
